### ISSUE TITLE
Make sure title of the blog post is displayed while sharing on Facebook

### ISSUE THREAD

**Issue by kracekumar** [pythonindia/inpycon-blog#10]
I shared the Dev Sprint page in fb https://www.facebook.com/kracekumar/posts/963189683733346,  but the page title didn't appear. 

Fix is simple, just add fb specific meta tag. https://developers.facebook.com/docs/sharing/best-practices#tags

**Comment by amitsin6h** [comment]
@kracekumar I tried to share the link in fb and am able to get the title

**Comment by amitsin6h** [comment]
![blog-fb-fetch](https://user-images.githubusercontent.com/12906090/31861943-59e02bec-b753-11e7-9c8b-c8e2e3bff4f4.jpg)

@kracekumar .. I think we should close this issue

**Comment by kracekumar** [comment]
👍

**Comment by realslimshanky** [comment]
@kracekumar blog lags some meta tags due to which telegram and other messaging platforms are unable to pick it up. It'll be great if someone can look it up.
