### ISSUE TITLE
Blog for Microsoft as Platinum Sponsor

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon-blog#106]
A Blog is needed to announce Microsoft as Platinum Sponsor like [0] and [1].
Write-up can be taken from [here](https://github.com/pythonindia/inpycon2017/blob/8dd58488ced5ffe01d7145b72bde9e62ae0a07c4/index.html#L731)
The Microsoft logo can be copied from [here](https://in.pycon.org/2017/images/sponsor/microsoft.png).
[0] https://in.pycon.org/blog/2017/announcing-tensorflow-platinum-sponsor.html
[1] https://in.pycon.org/blog/2017/announcing-hypertrack-platinum-sponsor.html

**Comment by abstract-mib** [comment]
I will do it.

**Comment by realslimshanky** [comment]
@abstract-mib please refer this [comment](https://github.com/pythonindia/inpycon2017/pull/180#issuecomment-340254393) for the query about image.

**Comment by realslimshanky** [comment]
Closing at it was fixed in #108
