### ISSUE TITLE
Github templates needed to helpout new contributors

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon-blog#128]
Github templates are needed to help out folks who are new and want to create an issue or raise pull request. These are the following work that need to be done
- [x] Add CONTRIBUTING.md
- [ ] Add link to CONTRIBUTING.md in README.md
- [ ] Add ISSUE_TEMPLATE.md
- [ ] Add PULL_REQUEST_TEMPLATE.md

**Comment by ananyo2012** [comment]
Maybe create a CONTRIBUTING.md similar to inpycon2018 website I am working here https://github.com/pythonindia/inpycon2018/pull/72 ?

**Comment by realslimshanky** [comment]
@ananyo2012 in addition to the files you are adding, few more will be needed inside `.github` folder in order to assist new contributors. We can take help from this article for that [Creating an issue template for your repository](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)

**Comment by a2un** [comment]
Hey..I am taking this up

**Comment by a2un** [comment]
Please find pull request https://github.com/pythonindia/inpycon-blog/pull/134

**Comment by ananyo2012** [comment]
@a2un I have updated the issue description. Please go ahead and complete the other tasks

**Comment by a2un** [comment]
Thank you @ananyo2012. That's good

**Comment by utkarsh2102** [comment]
@realslimshanky, shall I work on PULL_REQUEST_TEMPLATE?

**Comment by utkarsh2102** [comment]
Oh, okay.
Thought the user of inactive, hence asked.
No worries.
