### ISSUE TITLE
Adding a read more tag in blogs

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#136]
Since we are putting efforts to get more and more people to read the blog and increase traffic, I would like to suggest the use of "Read More" tags for the blog. This helps in improving both the UI/UX

Bloggers would know the benefit of this, the reader who lands on the blog would be able to see more than one post at any point of time and have to traverse fewer blogs too, if he is looking for other information. This is a problem since the webpage has become too long because of blog post of 2016/7. It's just a suggestion, all views on this are appreciated.  

The read more tag could be accomplished using the details tag in HTML

**Comment by ananyo2012** [comment]
+1 for the suggestion

**Comment by HarendraSingh22** [comment]
So on which of the blogs this should be done?
Maybe we can set a character limit and everything more than that is hidden in all the blogs?

**Comment by vipulgupta2048** [comment]
Yes, you can implement that as well, whatever works with pelican. 
Well, the blogs of 2018 for sure. If you can then 2017 as well. I guess that should do it.

**Comment by vipulgupta2048** [comment]
@ananyo2012 That's a great find, we can sure use that,
@HarendraSingh22 Can you take this up?

**Comment by vipulgupta2048** [comment]
@utkarsh2102 Can you take this up?

**Comment by utkarsh2102** [comment]
I don't think if I'll we able to take it as I've got no history with blogs.
However, I don't mind trying this. Where do we need the links to be inserted?

**Comment by vipulgupta2048** [comment]
The links would preferably be inserted after the first paragraph of the content or after giving out enough information for the reader to decide, understand the context and be intrigued enough to click `read more`

**Comment by Rohithgilla12** [comment]
Hey I would like to give it a shot,
Can I try it?
I'll see if I can work it out
P.S First time dealing with this stuff but I'll try my best

**Comment by utkarsh2102** [comment]
I'm not working on this issue.
@Rohithgilla12, you may proceed.

**Comment by ananyo2012** [comment]
@Rohithgilla12 Follow [this comment](https://github.com/pythonindia/inpycon-blog/issues/136#issuecomment-390501174) for the proposed solution

**Comment by ananyo2012** [comment]
Hmm just search how to add read more tags in pelican blog.

Also it would be great if you read the conversations in the issue while
taking up a task.

**Comment by realslimshanky** [comment]
I think this can be solved without even using a plugin. All one has to do is change the theme.
Simply crop the blog into say the first couple of sentences and add `<a>` tag after that. Check out how this theme uses the same methodology https://github.com/getpelican/pelican-themes/tree/master/aboutwilson
![aboutwilson](https://raw.githubusercontent.com/getpelican/pelican-themes/master/aboutwilson/screenshot.png)

**Comment by vipulgupta2048** [comment]
@realslimshanky  I like this way. 
@ananyo2012  Could we implement the same. This might be the DRY approach we are looking for.

**Comment by ananyo2012** [comment]
Yeah I am OK with anything as long as the end result is good.

**Comment by ananyo2012** [comment]
Is anyone working on this? otherwise I will take this up.

**Comment by vipulgupta2048** [comment]
Right, so what Satyakaam mentioned in the meeting was, that we implement pagination instead of `Read more ...` 
What do you think? I think we should go with both pagination and read more... 
Yes, you can take up the issue.

**Comment by vipulgupta2048** [comment]
While you choose which approach is right, please also add the links for `Speakers` and `Tickets` in the nav-bar

**Comment by ananyo2012** [comment]
> What do you think? I think we should go with both pagination and read more...

Yeah we should do both. 

> While you choose which approach is right, please also add the links for Speakers and Tickets in the nav-bar

Sure

**Comment by realslimshanky** [comment]
Let's keep both the options open for the contributor and hope for the best.

**Comment by ananyo2012** [comment]
So there is a issue with the pelican pagination. getpelican/pelican#1223 mentions it. I added summary changes and a failed attempt to add pagination in #150. Look at the changes.

**Comment by ananyo2012** [comment]
This can be closed now that #150 is merged. I had to do a hotfix to remove pagination as it is causing some issues in the production. I have to check that. Also now that we have summaries in place we need to put proper summaries for all older blog posts. I will open a new issue for that.
