### ISSUE TITLE
Bug: Hamburger menu for navbar not showing in mobile view

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon-blog#137]
Screenshot:
![screenshot from 2018-05-21 20-19-11](https://user-images.githubusercontent.com/10486343/40313877-77499736-5d34-11e8-9500-1bef91b5c11d.png)

**Comment by dhavalsavalia** [comment]
Hey,
I have fixed the issue! Check my pull request [https://github.com/pythonindia/inpycon-blog/pull/139](https://github.com/pythonindia/inpycon-blog/pull/139).
Screenshots of Google Chrome and Safari can be found [here](https://imgur.com/a/jYuYRjy).

**Comment by realslimshanky** [comment]
Closing this issue since it has been fixed in #139. Thank you @dhavalsavalia for your contribution :taco:
