### ISSUE TITLE
Add summaries for older blog posts

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon-blog#151]
After #150 we have a new way to add summaries to posts using `<!-- PELICAN_END_SUMMARY -->` markers instead of adding the summary in a `summary` key. Let's do this for all older blog posts that doesn't have this. This also helps to keep longer summaries.

**Comment by vipulgupta2048** [comment]
@ananyo2012 Good work !! Do add a blog post link for reference. 
@pythonindia/pycon-2018-team Please note in all future PR's that this is implemented to maintain consistency.

**Comment by vipulgupta2048** [comment]
Closing this as the purpose has been fulfilled
