### ISSUE TITLE
Add blog post for Google as Gold Sponsor

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon-blog#178]
**Category**: Gold Sponsor

Description: https://drive.google.com/open?id=1hmKJTqde2TvwAiB2JzCO8-9GMd1UxlSICGLd3gon0Lk
Logo: From PyCon India 2018 website repo

**Comment by Rohithgilla12** [comment]
This is asking for permission

**Comment by ananyo2012** [comment]
Can you try this link https://docs.google.com/document/d/1hmKJTqde2TvwAiB2JzCO8-9GMd1UxlSICGLd3gon0Lk/edit?usp=sharing

**Comment by ananyo2012** [comment]
Also probably you should be logged into your google account to view this.

**Comment by Rohithgilla12** [comment]
Got permission from the owner, will do PR after corteva is merged
