### ISSUE TITLE
Add blog post for Zeomega and DBS as Silver Sponsor

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon-blog#179]
**Category**: Silver Sponsor

This should go in single blog post

## Zeomega
Details at https://github.com/pythonindia/inpycon2018/issues/151#issuecomment-423069033

## DBS
Description: Yet to receive
Logo: From PyCon India 2018 website repo

**Comment by vipulgupta2048** [comment]
We would also be needing content for Jet Brains.

**Comment by vipulgupta2048** [comment]
Closing
