### ISSUE TITLE
Add Blog post for Zauba Cloud as gold sponsor

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon-blog#185]
Description:

Zauba Cloud is a next generation cloud computing platform that accelerates product development, reduces cost and increases overall performance and reliability of assets on public cloud and on premise data centres.
Zauba Cloud is the first cloud computing company to charge users based on actual usage of resources and not provisioned resources. Zauba Cloud's deep expertise and culture of exceptional engineering results in services designed for best in class performance and high availability.
Zauba Cloud offers free developer accounts. Developers can try and deploy their small projects in production for free.
Zauba Cloud is currently in preview and is invite only. Developers can write an email to cloud@zauba.company for access to preview.

Logo: from website repo

**Comment by Rohithgilla12** [comment]
Bro, Zauba cloud website link please 🙈

**Comment by ananyo2012** [comment]
https://zauba.company/ please update in the blog

**Comment by ananyo2012** [comment]
Also can you update google's link to https://developers.google.com/ in this PR ?

**Comment by Rohithgilla12** [comment]
I am not able to do the google link thingy bro 😢

**Comment by chirag200666** [comment]
@Rohithgilla12 
I've updated the Zauba cloud description, can you please create a blog post about the same.

**Comment by Rohithgilla12** [comment]
Completed

**Comment by vipulgupta2048** [comment]
@ananyo2012 I can take up adding the link since my opened PR deals with the same file. 
Closing this. Thanks for your contribution @Rohithgilla12 !!
:hatching_chick:

**Comment by vipulgupta2048** [comment]
#185 closed through #186
