### ISSUE TITLE
Some tweaking needed

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#189]
As we near the conference, we can work for executing the final touches. Here are some changes that could be made:- 
- Overflowing Google Developers logo in Desktop.
![screenshot_2018-09-30_16-57-19](https://user-images.githubusercontent.com/22801822/46257126-3b305680-c4d2-11e8-84ec-97d0846c02c7.png)
- The Devsprints blog to be linked with the Understanding Devsprints post to increase pingback. (Want to know what PyCon DevSprints, read this)  
- Since DevSprints are now paid, I recommend editing the Understanding DevSprints blog and adding the tickets link there as well.
- Updates the tickets blog, to be a reference for the next year's conference.  
- Go Jek logo is bit blurry (Should we swap it out for one of higher res or is it the one that was provided.)

Do recommend more, if you see one.

**Comment by ananyo2012** [comment]
Looks valid improvements. Lets work on them one by one. Do you want to take this up ?

**Comment by vipulgupta2048** [comment]
As #192 has been made, then I think the last two have been covered as well. 
Will work on the tickets blog later. 
Closing this.
