### ISSUE TITLE
Server stays running even after SIGINT

### ISSUE THREAD

**Issue by astronomersiva** [pythonindia/inpycon-blog#200]
Even after pressing `ctrl + c`, the server keeps running in the background.

This is annoying because while switching branches, random lines are printed in the shell and there seems to be no way to stop this as well(other than pressing `ctrl + c` each time this is done to recover the cursor)

<img width="723" alt="Screen Shot 2019-05-08 at 23 26 42" src="https://user-images.githubusercontent.com/7725225/57396776-c43a0980-71e8-11e9-8a84-8c12f6b2010e.png">

**Comment by gnurenga** [comment]
You can use below two command to solve this issue

### During development
`make devserver`

### To stop
`make  stopserver`

Note: You can find this two target in the `Makefile`

**Comment by astronomersiva** [comment]
Thanks for this @gnurenga! This is a real life saver to me for now :D

Having said that, I think we should make this a better experience because this repo will be worked on by non-devs(and devs without relevant experience) also.

The readme just tells that `./develop_server.sh start` will start the dev server. It is very reasonable to assume that the server will be killed when SIGINT is given by pressing `ctrl + c`. This is not the case here.  It won't be good to ask non-devs to run a separate command to stop a server. In my experience, as the number of commands to operate a software/tool increases, the number of people wanting to use that software/tool will decrease. Let's try and make this friendlier.

**Comment by gnurenga** [comment]
@astronomersiva There is one more option also is there

`./develop_server.sh   stop` After reading the usage i came to know.
1. In the shell script they are running the pelican server in the background. That is the reason ctrl+c didn't worked. 
2. Also they are running the pelican in auto reload and debug mode that is when ever a developer do a change and save it pelican regenerate the html file from markdown and serve the new output file.
3. If they don't run in background ideally when we use ctrl+c it will work. 
4. Any way shall I update and send a pull request for readme file.



```bash
$PELICAN --debug --autoreload -r $INPUTDIR -o $OUTPUTDIR -s $CONFFILE $PELICANOPTS &
```

**Comment by astronomersiva** [comment]
@gnurenga, I took a look at the script now.

I completely agree with what you are saying. However, the interesting thing here is that even though the server runs in the background(after SIGINT), **you cannot access the server** by visiting localhost:8000/blog in the browser. You need to actually run `./develop_server.sh` to visit it again. Which brings me back to my original question - what is the purpose of running a process in the background even after cleanup when it has no use at all.

Therefore, this looks more like a lack of proper cleanup than intentional behaviour to me. I did a simple grep and there are three different Pelican processes running in my machine now.

<img width="141" alt="Screen Shot 2019-05-10 at 22 04 34" src="https://user-images.githubusercontent.com/7725225/57542561-af3bb280-736f-11e9-9fe6-4fe0e076d145.png">

I did a one-line fix [here](https://github.com/pythonindia/inpycon-blog/pull/201) and after that:

- Development still works(live-reload and all)
- No stray Pelican processes like in the screenshot I have attached
- No interfering with the terminal when I switch branches.

**Comment by palnabarun** [comment]
> In my experience, as the number of commands to operate a software/tool increases, the number of people wanting to use that software/tool will decrease. Let's try and make this friendlier.

@astronomersiva Couldn't agree with this more. :+1:
