### ISSUE TITLE
Fix Netlify preview

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon-blog#268]
The Netlify Preview has broken css as the app get's deployed from root but the asset links are under `/blog` directory. Need to figure out a way to get the correct preview in Netlify.

**Comment by vipulgupta2048** [comment]
@pythonindia/pycon-india-2020-infrastructure had few points regarding Netlify, maybe you can take care of that as well with this issue. 

- Along with fixing the CSS, we were thinking of deploying the website on Netlify itself. Can you build the pipeline for it that way we can have a better, stable, more automated pipeline for the blog?
- Claim an account on Netlify with the PyCon email address and use that for the builds. 

What do you think?

**Comment by ananyo2012** [comment]
The point of having everything deployed from same server is to allow
minimum difficulty of registering urls with the PyCon India domain which is
linked to AFROST domain. Unless we have access of the domain account it is
difficult to do frequent changes with the website/blog where it's deployed
or if something goes wrong.

**Comment by palnabarun** [comment]
> The point of having everything deployed from same server is to allow
minimum difficulty of registering urls with the PyCon India domain which is
linked to AFROST domain. Unless we have access of the domain account it is
difficult to do frequent changes with the website/blog where it's deployed
or if something goes wrong.

I don't think it is a correct point. Why do you think we need to register an URL when deploying with Netlify?

**Comment by palnabarun** [comment]
> The point of having everything deployed from same server is to allow
minimum difficulty of registering urls with the PyCon India domain which is
linked to AFROST domain. Unless we have access of the domain account it is
difficult to do frequent changes with the website/blog where it's deployed
or if something goes wrong.

I don't think it is a correct point. Why do you think we need to register an URL when deploying with Netlify?

cc: @ananyo2012

**Comment by palnabarun** [comment]
> Claim an account on Netlify with the PyCon email address and use that for the builds.

I have claimed an account with the same already. :)

**Comment by ananyo2012** [comment]
Also I think I would rather prefer a static gh-pages website instead of
netlify for the entire website setup

**Comment by palnabarun** [comment]
> Also I think I would rather prefer a static gh-pages website instead of
netlify for the entire website setup

What is the reason for that? You are putting your eggs in Github's basket rather than Netlify's basket. GH sees a lot more outages these days than Netlify.

**Comment by ananyo2012** [comment]
> The point of having everything deployed from same server is to allow
> minimum difficulty of registering urls with the PyCon India domain which is
> linked to AFROST domain. Unless we have access of the domain account it is
> difficult to do frequent changes with the website/blog where it's deployed
> or if something goes wrong.
>
> I don't think it is a correct point. Why do you think we need to register
> an URL when deploying with Netlify?
>

We need to back link the netlify domain from AFROST PyCon India domain
right ? Do we have access to that ?

>

**Comment by ananyo2012** [comment]
On Thu, 21 May, 2020, 11:53 PM Nabarun Pal, <notifications@github.com>
wrote:

> Also I think I would rather prefer a static gh-pages website instead of
> netlify for the entire website setup
>
> What is the reason for that? You are putting your eggs in Github's basket
> rather than Netlify's basket. GH sees a lot more outages these days than
> Netlify.
>
gh-pages give more fine tuning in terms of CI. Is their enough flexibility
related to that in Netlify ? I haven't used Netlify extensively, mostly use
it for previews.

Also if we are going to use git submodules for the entire website won't it
be better to use gh-pages itself ?

>

**Comment by palnabarun** [comment]
> We need to back link the netlify domain from AFROST PyCon India domain
right ? Do we have access to that ?

What do you mean by "back link"?

> gh-pages give more fine tuning in terms of CI.

I may be wrong but does gh-pages have a CI?

> Also if we are going to use git submodules for the entire website won't it
be better to use gh-pages itself ?

How is coding convention related to deployment methodology?

**Comment by astronomersiva** [comment]
> The Netlify Preview has broken css as the app get's deployed from root but the asset links are under /blog directory. Need to figure out a way to get the correct preview in Netlify.

@ananyo2012, we had this issue while working on the last year's edition as well. The solution was to edit the build command in Netlify. We ended up moving the output files to a directory named `blog`. IIRC, it was something like this:

`buildCommand && mkdir newPathToDeploy && mv outputDir newPathToDeploy/blog && echo "<a href='/blog'>see your changes here</a>" > newPathToDeploy/index.html`


After this, you will have to configure Netlify to have `newPathToDeploy` has the `publishDirectory` instead of whatever it is currently.

**Comment by ananyo2012** [comment]
> > We need to back link the netlify domain from AFROST PyCon India domain
> > right ? Do we have access to that ?
> 
> What do you mean by "back link"?
> 
I mean adding CNAME / A records for the website in AFROST's domain provider. 
> > gh-pages give more fine tuning in terms of CI.
> 
> I may be wrong but does gh-pages have a CI?
> 
I was referring to GitHub Actions. But we can also setup CI in GitHub Actions and deploy it to Netlify using Netlify. Just wanted to explore all options.

> > Also if we are going to use git submodules for the entire website won't it
> > be better to use gh-pages itself ?
> 
> How is coding convention related to deployment methodology?

Netlify uses single build command so I was a bit concerned How the submodules thing would work out. But we can have a build script to manage everything.

@palnabarun I did some searching myself and this was a good exercise for me to know the various deployment options. So the requirement is to have some CI/CD setup and use a appropriate deployment platform. Netlify seems to be a good choice. It would be good if we can document the requirements and steps for the move keep it in the handbook for future references.

One requirement is to have access to the PyCon India Domain provider account so that we can easily make changes to the CNAME records when required. The earlier strategy used a single server which was always linked to the Domain and everything was done there. So this will be one more additional access to get.

**Comment by ananyo2012** [comment]
Btw the intention of this issue is just to fix the preview problem. Thanks @sivaa For the suggestion. I will try that out and update.

@palnabarun I have created https://github.com/pythonindia/inpycon2020-tasks/issues/42 . We can continue discussion there

**Comment by palnabarun** [comment]
@astronomersiva There's a simpler solution to the preview problem. Ref: https://github.com/pythonindia/inpycon-blog/pull/272

**Comment by astronomersiva** [comment]
@palnabarun, just curious if [this change](https://github.com/pythonindia/inpycon-blog/pull/272/files#diff-8ef79b47062ce86f791c2983b23e36c1R10) will cause the blog to look for css files at in.pycon.org/theme/css/styles.css. I believe this will break the blog once it's deployed to the prod server.

However, I think your solution can be fixed to make this work. If you make use of env variables(`process.env` in Node.js) to change `SITEURL` in pelicanconf.py to either `/` or `/blog` depending on the deployment platform, things will work.

**Comment by palnabarun** [comment]
@astronomersiva You got it right. :+1:

The production deployment happens through `publishconf.py` though.

**Comment by palnabarun** [comment]
@ananyo2012 You can't CNAME subpaths. DNS records are for domains/subdomains not for URL paths.

**Comment by ananyo2012** [comment]
@palnabarun Yes you are right. I meant if we move to netlify we need to CNAME the netlify url in the Domain account.

**Comment by palnabarun** [comment]
No, we don't need to.

**Comment by palnabarun** [comment]
The previews are fixed now with #272 

Hence, closing.
