### ISSUE TITLE
Update of metadata of blog website

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#278]
Update title, description of the website for a better social media preview.

`in.pycon.org/blog` has title set as `In Pycon blog` which looks shabby. 

Solution: Update `og:title` tags + `pelicanconf.py`

**Comment by kapilsharma432001** [comment]
Ok I'll do that...Assign this to me.

**Comment by vipulgupta2048** [comment]
Thanks @kapilsharma432001 for showing your interest. From next time onwards, just make a PR after pinging on the issue. Thanks!

**Comment by kapilsharma432001** [comment]
@vipulgupta2048  Ok thank you. But I am facing an issue related to **make server ** command.
Following is the issue:-
"$ make serve
pelican --listen --autoreload C:/Users/Kapil Sharma/inpycon-blog/content --settings C:/Users/Kapil Sharma/inpycon-blog/pelicanconf.py --port 8000 --bind 127.0.0.1
usage: pelican [-h] [-t THEME] [-o OUTPUT] [-s SETTINGS] [-d] [-v] [-q] [-D]
               [--version] [-r]
               [--print-settings [SETTING_NAME [SETTING_NAME ...]]]
               [--relative-urls] [--cache-path CACHE_PATH] [--ignore-cache]
               [-w SELECTED_PATHS] [--fatal errors|warnings]
               [--logs-dedup-min-level {DEBUG,INFO,WARNING,ERROR}] [-l]
               [-p PORT] [-b BIND]
               [path]
pelican: error: unrecognized arguments: Sharma/inpycon-blog/content Sharma/inpycon-blog/pelicanconf.py
make: *** [serve] Error 2
"

**Comment by ananyo2012** [comment]
Please clone the repo in C:\Users directory. This is the typical issue with
windows where it allows folder name with spaces and user has to put quotes
around the pathname for directory name with spaces in it.

**Comment by kapilsharma432001** [comment]
Now I am facing Permission error.

**Comment by ananyo2012** [comment]
Can you post the logs ? Unless you can in C:\ directory you shouldn't be
facing issues.

**Comment by kapilsharma432001** [comment]
@ananyo2012 
`$ make serve
pelican --listen --autoreload C:/inpycon-blog/content --settings C:/inpycon-blog/pelicanconf.py --port 8000 --bind 127.0.0.1
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
CRITICAL: TypeError: can't pickle generator objects
make: *** [serve] Error 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\kapil sharma\appdata\local\programs\python\python37\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\users\kapil sharma\appdata\local\programs\python\python37\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
`

**Comment by kapilsharma432001** [comment]
@ananyo2012 
**$ make serve
pelican --listen --autoreload C:/inpycon-blog/content --settings C:/inpycon-blog/pelicanconf.py --port 8000 --bind 127.0.0.1
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
CRITICAL: TypeError: can't pickle generator objects
make: *** [serve] Error 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\kapil sharma\appdata\local\programs\python\python37\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\users\kapil sharma\appdata\local\programs\python\python37\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
**

**Comment by ananyo2012** [comment]
Have you tried googling the issue ?

**Comment by ananyo2012** [comment]
Anyways I searched and found this is an issue with windows in the current pelican version and is fixed in the next pelican release - https://github.com/getpelican/pelican/issues/2400.

For now build the site using `make publish` and then use `pelican -l` to start the server
