### ISSUE TITLE
make serve fails in Windows

### ISSUE THREAD

**Issue by ananyo2012** [pythonindia/inpycon-blog#279]
This issue was reported in #278 originally. `make serve` fails in Windows with the following error

```
**$ make serve
pelican --listen --autoreload C:/inpycon-blog/content --settings C:/inpycon-blog/pelicanconf.py --port 8000 --bind 127.0.0.1
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
CRITICAL: TypeError: can't pickle generator objects
make: *** [serve] Error 1
Traceback (most recent call last):
File "", line 1, in
File "c:\users\kapil sharma\appdata\local\programs\python\python37\lib\multiprocessing\spawn.py", line 99, in spawn_main
new_handle = reduction.steal_handle(parent_pid, pipe_handle)
File "c:\users\kapil sharma\appdata\local\programs\python\python37\lib\multiprocessing\reduction.py", line 87, in steal_handle
_winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] Access is denied
**
```
This is a issue in pelican v4.2.0 - Ref: https://github.com/getpelican/pelican/issues/2400 . This is fixed in pelican master as is supposed to be available in next release of pelican. Till then we need to fix it the make serve target.

A proposed fix is to not use autoreload if OS is Windows. Using only `pelican -l` works. So use `make html` to publish the website and `make serve` should be updated to use `pelican -l` if OS is Windows.

**Comment by vipulgupta2048** [comment]
@ananyo2012 Should I assign you for fixing this or can you work towards making a workaround for Windows users?
