### ISSUE TITLE
Design and development of Blog Page and Blog Index Page

### ISSUE THREAD

**Issue by SaptakS** [pythonindia/inpycon-blog#280]
We need a design that can be used in the current blog:
- [ ] the blog index page which would show a list of all blogs with 
       - a excerpt
       - the title
       - published date
       - author
       - read more link
- [ ] the blog page, with the design based on the current blogs.

Current blog link: https://in.pycon.org/blog/

**Comment by SiddharthSimharaju** [comment]
Figma Link for blog design: 
https://www.figma.com/file/l3fowoKJ1OAyXRd7j095r5/PyconIND-Assets?node-id=164%3A1765

**Comment by vipulgupta2048** [comment]
@ananyo2012 Should we close this?

**Comment by vipulgupta2048** [comment]
Closing in favor of #282
