### ISSUE TITLE
Summary feature broke for 2020 posts

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#283]
Pelican Summary works for all posts, except 2020 posts from the last update. 
Needs a hotfix.

**Comment by ananyo2012** [comment]
The summary feature seems to be broken. It's not working for any posts. @vipulgupta2048 Can you investigate the issue ?

**Comment by vipulgupta2048** [comment]
I unassigned myself thinking, we can get some of the new contributors to take it up. 
My bandwidth is full at the moment. Will take a look as soon as I get time.

**Comment by ritesh-pandey** [comment]
I took a look at the issue. The summary plugin and pelican version are out of sync.
I updated the plugin version locally and summary feature started to work again.

Let me know if you want me to create a PR.

**Comment by ananyo2012** [comment]
Please go ahead and make a PR

**Comment by vipulgupta2048** [comment]
Update: I will be taking a look for this.
