### ISSUE TITLE
Add Anchor tags to link headings 

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#284]
We need the Pelican blogs to have anchor tags to link specific content as needed.
This would be mighty helpful as we link information in other blogs, social media and website pages.

**Comment by ananyo2012** [comment]
Can you give some examples of the feature ?

**Comment by vipulgupta2048** [comment]
![Screenshot_2020-07-27_23-06-08](https://user-images.githubusercontent.com/22801822/88573077-cd1d3200-d05d-11ea-8b88-b6953b32936d.png)
@ananyo2012 Anchors something like this which we can use to link down headings https://virtualfish.readthedocs.io/en/latest/plugins.html#virtualenvwrapper-compatibility-aliases-compat-aliases

**Comment by vipulgupta2048** [comment]
We would like to add the same feature to our Pelican blog so that we can refer to the information more accurately when we start writing the guide for folks! First step to solving the issue would be to check the feasibility if we can even add the anchor tag using the tools provided by Pelican only. If not, we can look forward to building our own custom implementation of the same.
