### ISSUE TITLE
Fix design issues and optimize for accessibility 

### ISSUE THREAD

**Issue by Sc0rpi0n101** [pythonindia/inpycon-blog#293]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
The spacing between the headings and their content is not enough. It's not even a line break worth of space, as visible in the current blogs, for eg. https://in.pycon.org/blog/2020/announce-pycon-india-mentorship.html. 

The spacing looked fine on the About page build(https://deploy-preview-35--gifted-sinoussi-aa5f01.netlify.app/about), but I had to leave 2 blank lines to get proper spacing.

**Comment by vipulgupta2048** [comment]
In addition to the issue opened, more things to take care of

- [ ] Update font-family or improve on font presentation
- [ ] Review and improve the CSS for any more changes that leads to improvements. 
- [ ] Tag the design team when making the PR
- [ ] Run Lighthouse on the side after pagination PR is merged to improve more on performance and accessibility as suggested over on #270 
- [ ] Improve margins over images and other content

**Comment by vipulgupta2048** [comment]
Any update? @Sc0rpi0n101

**Comment by vipulgupta2048** [comment]
Any update? @Sc0rpi0n101
