### ISSUE TITLE
Social media icons does not link to correct social media pages

### ISSUE THREAD

**Issue by iamkhush** [pythonindia/inpycon-blog#297]
* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Upon clicking the fb and twitter icons, the page it doesnt send me anywhere, it just opens the same page.

* **If the current behavior is a bug, give an appropriate description of the bug, steps to reproduce it and attach screenshots or use similar means for the same.** 
Go to https://in.pycon.org/blog/2020/2020-call-for-volunteers.html.
Scroll to the bottom of the page, You will find twitter and fb icons. 
Click either of them.

* **What is the expected behavior?**
 It should send me to the correct fb and twitter urls.

* **What is the motivation / use case for changing the behavior?**
Easy access to social media pages.

* **Please tell us about your environment:**
  
  - Browser: All

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, etc)

**Comment by vipulgupta2048** [comment]
Thanks @iamkhush for opening this issue, would you be willing to take this up, submit a PR so I can assign you. Also, it would be great if you can add some more icons and their corresponding social media handles. 
Icons can be found here https://drive.google.com/drive/folders/1FGisVxBKXdPiGVOkkHA6r71Q2VBuR-us?usp=sharing

What we need is Facebook, Twitter, Linkedin, Zulip, and the mailing list.

**Comment by iamkhush** [comment]
Sure, would be happy to help :) . Please assign it to me

**Comment by iamkhush** [comment]
@vipulgupta2048 the pr is ready to merge. Have a look when you get a chance
