### ISSUE TITLE
Add FontAwesome icon for pagination

### ISSUE THREAD

**Issue by vipulgupta2048** [pythonindia/inpycon-blog#300]
* **Do you want to request a *feature* or report a *bug*?**
At this moment, we don't have an icon for our pagination arrows. You can pick icons from wherever you like that would match our theme. When selected, add them to blogs from here.

https://github.com/pythonindia/inpycon-blog/blob/fb13e337d9cab1c993349accd94cbd5058337532/themes/inpycon2020/templates/pagination.html#L8

![Screenshot from 2020-08-06 22-50-04](https://user-images.githubusercontent.com/22801822/89562191-3ad41580-d837-11ea-8418-9b66637343f4.png)

Check this out for reference Can we use this icon over here https://fontawesome.com/icons/angle-double-right?style=solid

**Comment by JeanMarcSaad** [comment]
I'll be working on that!

**Comment by JeanMarcSaad** [comment]
Implemented in PR #303

**Comment by vipulgupta2048** [comment]
Thanks @JeanMarcSaad for the PR
Closing via #303
