### ISSUE TITLE
Update to Outreach Partner post

### ISSUE THREAD

**Issue by anistark** [pythonindia/inpycon-blog#301]
Need to add notes section to the [post](https://in.pycon.org/blog/2020/2020-outreach-partners.html).

Ref: https://github.com/pythonindia/inpycon2020-tasks/wiki/Outreach-Partners#note

Also, should we update the title?

**Comment by abhishekmishragithub** [comment]
@Sc0rpi0n101 @vipulgupta2048 can you please update the changes, it's quiet urgent.

**Comment by Sc0rpi0n101** [comment]
Sure, doing it now

**Comment by Sc0rpi0n101** [comment]
Please check #302

**Comment by Sc0rpi0n101** [comment]
Also, should I add this to the mail template in the handbook too?

**Comment by abhishekmishragithub** [comment]
> Also, should I add this to the mail template PR in the handbook too?

Yes.

**Comment by Sc0rpi0n101** [comment]
https://github.com/pythonindia/pyconindia-handbook/pull/31

**Comment by anistark** [comment]
Who has access to merge it?

**Comment by Sc0rpi0n101** [comment]
> Who has access to merge it?

@vipulgupta2048 @palnabarun

**Comment by Sc0rpi0n101** [comment]
#302  was merged with the changes. This can be closed.
