### ISSUE TITLE
Make "Read More →" button and make Summary with limited words

### ISSUE THREAD

**Issue by kmlhsn** [pythonindia/inpycon-blog#304]
* **Do you want to request a *feature* or report a *bug*?**
request a *feature*:
1. Make  "Read More →"  Twitter bootstrap button
2. Make length of words/characters limited in Summery/brief   
* **What is the current behavior?**

1. "Read More →" is a HTML anchor now
 2. Summery/brief has unlimited words now.  some Summery/brief is within few words and some Summery/brief has many words

* **If the current behavior is a bug, give an appropriate description of the bug, steps to reproduce it and attach screenshots or use similar means for the same.** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
OS: Windows 10
Browser: Mozilla Firefox 79
  
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [Markdown | reStructured text | Python]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, etc)
![image](https://user-images.githubusercontent.com/32615215/90166670-6c5f5a80-ddbc-11ea-81ca-3c761f35ee1c.png)
![image](https://user-images.githubusercontent.com/32615215/90168491-fa3c4500-ddbe-11ea-96a6-5f7e27e1c985.png)

**Comment by vipulgupta2048** [comment]
Thanks @kmlhsn for opening an issue regarding the same. Would you like to take it up and submit a PR?

**Comment by kmlhsn** [comment]
> 
> 
> Thanks @kmlhsn for opening an issue regarding the same. Would you like to take it up and submit a PR?

Sorry. I fail to run the website from my PC(Local Machine).  I don't know how to "make serve".

**Comment by vipulgupta2048** [comment]
Hi @kmlhsn no worries, we can help you out. `make serve` is a command that you have to enter in your terminal/command prompt after installing the dependencies.

**Comment by kmlhsn** [comment]
> 
> 
> Hi @kmlhsn no worries, we can help you out. `make serve` is a command that you have to enter in your terminal/command prompt after installing the dependencies.

ok. i have installed the dependencies. Please tell me next steps

**Comment by vipulgupta2048** [comment]
@kmlhsn You can check the `themes/inpycon2020` directory for the theme used for this and work from there on resolving the issue.

**Comment by vipulgupta2048** [comment]
This is resolved by using the right summary frontmatter tag. Closing.
