### ISSUE TITLE
Typo in Writing a proposal for PyCon India? Our Mentorship team is here to help! blog post

### ISSUE THREAD

**Issue by Skchoudhary** [pythonindia/inpycon-blog#368]
* **Do you want to request a *feature* or report a *bug*?**
Bug

Blog post link: https://in.pycon.org/blog/2021/announce-mentorship.html
The Reviewing Proposals section of the blog post  

```
If you don't get any response in 48 hours, please send a ollow up message to #wg/mentorship on Zulip.
```
it should be
```
If you don't get any response in 48 hours, please send a follow up message to #wg/mentorship on Zulip. 
```

**Comment by vipulgupta2048** [comment]
Thanks @Skchoudhary for pointing this out. Please do create a PR for patching this up if you can.

**Comment by Skchoudhary** [comment]
@vipulgupta2048  sure will do that

**Comment by vipulgupta2048** [comment]
Closing in favor of #369
