### ISSUE TITLE
About Tab is not working

### ISSUE THREAD

**Issue by soumendrak** [pythonindia/inpycon-blog#424]
The About tab is redirecting to 404.

https://in.pycon.org/2023/about/

![image](https://github.com/pythonindia/inpycon-blog/assets/10120538/0f9d3aeb-69e2-4c73-9def-04bc86bb9711)

Is this tab required?

**Comment by bhansa** [comment]
Yes, we are yet to create an About Us page on pycon site, https://github.com/pythonindia/inpycon2023/issues/105

**Comment by sayanchowdhury** [comment]
Closing this issue as invalid
