### ISSUE TITLE
Add Blog on YLW, Tinkering Space events

### ISSUE THREAD

**Issue by bkamapantula** [pythonindia/inpycon-blog#429]
**Young Learner events at PyCon India: Young Learners Workshop and Tinkering Space**

PyCon India is proud to introduce two exciting events aimed at diversifying the conference experience and nurturing innovation: the Young Learners Workshop (YLW) and Tinkering Space.

**Young Learners Workshop (YLW): Fostering Future Coders**
Our Young Learners Workshop empowers middle-high school students to engage with Python programming using Raspberry Pi devices. With a focus on cultivating coding, communication, and tech skills, YLW fosters collaboration between students, teachers, and the Indian Python community. Hosted by Harsh Mittal, this free workshop welcomes 50 students to explore, learn, and share.

**Tinkering Space: Where Creativity Meets Innovation**
The Tinkering Space invites parents and children to embark on a captivating journey of hands-on tinkering with cutting-edge hardware. Unleash imagination as you experiment with Raspberry Pi Pico, sensors, connectors, and more. Join Anitha Raman and Manav Sethi for this full-day event that promotes shared learning and innovation.

Both events adhere to PyCon India's [Code of Conduct](https://in.pycon.org/2023/code-of-conduct/), ensuring an inclusive and safe environment. Don't miss out! Register now:

- [Young Learners Workshop Registration](https://pythonexpress.org/young-learners-workshop/)
- [Tinkering Space Registration](https://konfhub.com/pyconindia2023)

Read more about the events:
- [Young Learners Workshop](https://in.pycon.org/2023/ylw/)
- [Tinkering Space](https://in.pycon.org/2023/tinkering-space/)

Ignite curiosity, bond with your children, and shape the future at PyCon India. For queries, contact us at contact@in.pycon.org.

**Comment by sayanchowdhury** [comment]
Closing this issue as invalid.
