### ISSUE TITLE
[PyCon India] Dev Sprint Venue Request

### ISSUE THREAD

**Issue by harisibrahimkv** [pythonindia/inpycon-blog#444]
Hello `<individual>`!

Hope this mail finds you in the best of health and spirits.

Introduction
----------------
If you haven't heard already, preparations are in full swing to get PyCon India 2024 (https://in.pycon.org/2024/) in shape to be held from 20th - 23rd September at Bangalore. It is one of the biggest gatherings of Python enthusiasts in India during that one time of the year. It has representation from different parts of the world as keynotes, attendees and open source project contributors.

Which brings us to the gist of this mail.

Dev Sprints
---------------
We dedicate one entire day of the conference to conducting a Dev Sprint - 23rd September. It is a one day event where core maintainers & contributors of multiple Python projects will be present. By the time the day ends, a lot of people would've done their first open source contribution, a lot of open issues would've been addressed and a lot of projects would be at a better place than they were at the start of that day.

The way it creates a culture of collaboration and support is truly amazing. If you haven't been a part of one yet, we hereby wholeheartedly extend an invitation. The registration details should soon be up on the website.

Which brings us to the request that we have.

The Request
-----------------
Would `<company@xyz>` be willing to support us by providing a venue for the event?

Requirements
-------------------
For what we've planned, the minimum requirements would be:
1. Date: 23/09/2024
2. Time: 9AM to 5PM (a buffer of ~1 hour before and after for setup and cleanup)
3. Capacity: 120 - 200 people.
4. Seating and power outlets for participants.
5. Internet.
6. Power backup.
7. Tea / Coffee throughout the day.
8. One projector.

Additionally, it'd be nice to have:
1. Mics + audio setup (makes it easier to do announcements).
2. Lunch + Snacks.
3. Separate rooms that can facilitate smaller breakout groups for discussions.

Perks
-------
While good karma is one that goes without saying, `<company@xyz>` will be officially announced as our "venue sponsor" on our website, social media and other communication channels. You'll also have have a dedicated 30 minute slot to speak about your organization on the day of the Dev Sprint.

Wrapping up
-----------------
If you're convinced already, great! If you have more questions, do feel free to reach out.

Regardless though, thank you for being one among those in our minds whom we could reach out to.

Sincerely,
The PyCon India Team

**Comment by anistark** [comment]
I believe this was done.
