### ISSUE TITLE
[PyCon India] Community Partners

### ISSUE THREAD

**Issue by harisibrahimkv** [pythonindia/inpycon-blog#445]
# Announcement

It didn't start as PyCon India.

It started when a bunch of people, quite out of nowhere, met. It started with them talking and realizing about something that they all loved. It started when these people started spreading that love by teaching, supporting and welcoming others into their hood - the community that they had created.

We run the `Community Partners Program` every year as a part of PyCon India. The goal is to further strengthen and help grow the various communities around the country by remembering what it is that made us what we are today.

We aim for:
- Collaboration: To support and help with organizing events as well as discussion of ideas for growth.
- Outreach: To further spread the word about PyCon india through various communities around India.
- Diversity & inclusion: To keep knowledge, help and humanity as our core principle - regardless of whoever you are and wherever you're from.

The various groups who could potentially become a community partner are:
- Open-Source Organizations: Projects that contribute to the tech community through the development of open-source libraries, frameworks, tools, or software.
- Non-Profit Organizations: Non-profit entities dedicated to promoting technology and supporting developers.
- Technology communities and user groups: Local or regional Python user groups, developer communities, or tech-focused organizations that engage and support tech enthusiasts.

If you see the community that you are a part of fitting the description above, then here's how we can collaborate:

What you can expect from us:
- Special discount coupons for a bunch of your community members.
- A shout out to your community in both the opening and closing speeches of the conference.
- Your community logo on the official PyCon India website (https://in.pycon.org/2024/)
- Access to Community Open Space to engage with the attendees.

What we expect from you:
- Introduce PyCon India to your community both via your events and your social media channels.
- Regularly share updates about the conference with your members.
- Follow the conference's Code of Conduct at all times.

Sounds good? Then let's help each other out. Let us know by filling this form: https://dub.sh/inpy24com

With hope and love,
The PyCon India Team.

# Mail

It didn't start as PyCon India.

It started when a bunch of people, quite out of nowhere, met. It started with them talking and realizing about something that they all loved. It started when these people started spreading that love by teaching, supporting and welcoming others into their hood - the community that they had created.

We are reaching out to you knowing that it is with the same passion, love and support that you're building the community that you're a part of.

We run the `Community Partners Program` every year as a part of PyCon India. The goal is to further strengthen and help grow the various communities around the country by remembering what it is that made us what we are today. The "we"s and "you"s are just in words. What matters is "us".

We aim for:
- Collaboration: To support and help with organizing events as well as discussion of ideas for growth.
- Outreach: To let you and the folks around you know about us and to let us and the folks around us know about you.
- Diversity & inclusion: To keep knowledge, help and humanity as our core principle - regardless of whoever you are and wherever you're from.

What you can expect from us:
- Special discount coupons for a bunch of your community members.
- A shout out to your community in both the opening and closing speeches of the conference.
- Your community logo on the official PyCon India website (https://in.pycon.org/2024/)
- Access to Community Open Space to engage with the attendees.

What we expect from you:
- Introduce PyCon India to your community both via your events and your social media channels.
- Regularly share updates about the conference with your members.
- Follow the conference's Code of Conduct at all times.

Sounds good? Then let's help each other out. Do fill out https://dub.sh/inpy24com and let us know.

With hope and love,
The PyCon India Team.

# Social Media

### Twitter

The `Community Partners Program` is live and we're inviting you to be a part of it! If you're someone doing your part in building a community, and you're interested in joining forces with us to make it happen, let us know - https://dub.sh/inpy24com

Further details at: https://drive.google.com/file/d/17P7CaYvOghF8WGm1QtVT6jK162SyTBph/view

### Rest of ''em

We remember our past, we learn from it and we act on it. PyCon India wouldn't be what it is today without the community that it is built on top of. In its spirit and to nurture it, we launched the `Community Partners Program` and we're inviting you to be a part of it. If you're someone doing your part in building a community, and you're interested in joining forces with us to make it happen, let us know - https://dub.sh/inpy24com

Further details at: https://drive.google.com/file/d/17P7CaYvOghF8WGm1QtVT6jK162SyTBph/view

**Comment by Sc0rpi0n101** [comment]
Looks great, thank you. 

I'm not so sure about the Unrelated or Unfitting Groups tho. 

And I have a suggestion for the twitter stuff, let me know how this sounds. 

``` 
Calling all community builders! Our Community Partners Program is back, and we're inviting you to be a part of it! If you're someone doing your part in building a community, and you're interested in joining forces and making a difference together, fill out the form now! - https://dub.sh/inpy24com
```

**Comment by harisibrahimkv** [comment]
@Sc0rpi0n101 

+1 for the Twitter content.

The `Unrelated or Unfitting Groups` part did feel weird to read. My assumption was that we would need all of what was here - https://drive.google.com/file/d/17P7CaYvOghF8WGm1QtVT6jK162SyTBph/view.

If not, then I personally feel that removing the entire `Those who potentially could NOT become a community partner are:` would be best.

**Comment by Sc0rpi0n101** [comment]
> The `Unrelated or Unfitting Groups` part did feel weird to read. My assumption was that we would need all of what was here - https://drive.google.com/file/d/17P7CaYvOghF8WGm1QtVT6jK162SyTBph/view.

I feel like we should include this prospectus link in the social media announcements, too, so that people can get more info here. The form doesn't link to this file. Maybe add it to the form also.

> If not, then I personally feel that removing the entire `Those who potentially could NOT become a community partner are:` would be best.

I agree.💯

**Comment by harisibrahimkv** [comment]
- Removed `Those who potentially could NOT become a community partner are:`
- Updated Twitter content with your version
- Updated both Twitter and other SM content with the link to the prospectus.

What you'll have to do:
- Shorten link to the prospectus
- Add link to the form (if needed)

**Comment by Sc0rpi0n101** [comment]
I'm not sure who can edit the form. 
@anistark can you add the prospectus link there?

**Comment by Sc0rpi0n101** [comment]
This is the link: https://navigator.in.pycon.org/en/latest/participate/community-partner.html

**Comment by harisibrahimkv** [comment]
@Sc0rpi0n101 That navigator link has a different content though and it has that `Those who potentially could NOT become a community partner are:`

Should that be updated with the content we've prepared?

**Comment by Sc0rpi0n101** [comment]
I still think that section has no place in the announcement. 
We're adding the navigator link everywhere. So people can read it for more details. 

If there are any details discrepancies, then we should change the content.

**Comment by anistark** [comment]
I believe the link is in form already.

**Comment by anistark** [comment]
We can share form link. Navigator link is in form itself.

**Comment by WatchfulHitman** [comment]
> Looks great, thank you.
> 
> I'm not so sure about the Unrelated or Unfitting Groups tho.
> 
> And I have a suggestion for the twitter stuff, let me know how this sounds.
> 
> ```
> Calling all community builders! Our Community Partners Program is back, and we're inviting you to be a part of it! If you're someone doing your part in building a community, and you're interested in joining forces and making a difference together, fill out the form now! - https://dub.sh/inpy24com
> ```

This is exceeding the limit for Twitter

**Comment by harisibrahimkv** [comment]
@WatchfulHitman 

You can use the version at the top?
```
The Community Partners Program is live and we're inviting you to be a part of it! If you're someone doing your part in building a community, and you're interested in joining forces with us to make it happen, let us know - https://dub.sh/inpy24com
```

This is at 246.

**Comment by Sc0rpi0n101** [comment]
I think he already tweeted it.

**Comment by anistark** [comment]
I believe this was done.
