### ISSUE TITLE
[PyCon India] Sponsor Blog: Add Happyfox Blog for Platinum Sponsors 

### ISSUE THREAD

**Issue by abhishekmishragithub** [pythonindia/inpycon-blog#453]
Tier: Platinum 
Name of the Company: HappyFox Inc 
Description:
"HappyFox is a leading provider of AI-driven support solutions, committed to exceptional customer and employee experiences. Our products include Help Desk, Service Desk, Assist AI, Workflows, Live Chat, Chatbot, and Business Intelligence.

New Product Update: HappyFox AI enhances support operations with AI Copilot, AI Insights, AI Knowledge Base, AI Resolve, and AI Agents.

Trusted by over 2,000 companies in 70+ countries, HappyFox empowers support teams in customer service, IT, HR, facilities, and more with user-friendly solutions that simplify complexity and encourage collaboration.

Careers at HappyFox: We prioritize meaningful connections and career growth, offering flexibility, autonomy, and transparency. Our dynamic environment supports development and our motto is: Happy employees, happy customers. Explore job openings at happyfox.com/jobs in Chennai, Bangalore and Hyderabad."

Company Website URL: https://happyfox.com 
twitter handle: HappyFoxApp 
Linkedin: https://www.linkedin.com/company/happyfox-inc-/ 
logo : https://drive.google.com/open?id=1dG4yx8nOEaRwv5Jd4fftUOoEsqImRJky

**Comment by abhishekmishragithub** [comment]
@Sc0rpi0n101 ^

**Comment by abhishekmishragithub** [comment]
moving it to the task repo

**Comment by anistark** [comment]
I believe this was done.
