### ISSUE TITLE
Add social share button to post single page

### ISSUE THREAD

**Issue by theskumar** [pythonindia/inpycon-blog#58]
Few things that I have in mind:

https://sharebutton.co/
https://www.kurtnoble.com/labs/rrssb

**Comment by amitsin6h** [comment]
@theskumar let me take this

**Comment by amitsin6h** [comment]
@realslimshanky @theskumar can you tell me where I can keep the button at bottom or in top.
Or what I was thinking that we can keep the floating share button at right side. Let me know what you think

**Comment by realslimshanky** [comment]
The button can be placed after the title or the end of the blog at the center.
