### ISSUE TITLE
[UI] Display is breaking on mobile view

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon-blog#70]
Due to the images being non-responsive to the window width the display is breaking.
Need to make the width response with respect to window size.
![screenshot](http://i.imgur.com/XUO2Vjh.png)

**Comment by amitsin6h** [comment]
let me take this @realslimshanky

**Comment by realslimshanky** [comment]
@amitsin6h Please work on the issue and discuss whatever query you have here only.

**Comment by amitsin6h** [comment]
https://www.amcharts.com/kbase/making-charts-responsive/
Best way to make amcharts responsive was to edit amcharts configuration but it is not possible as we are parsing the feed. but it can done from the source file.

I have just managed to display amcharts in mobile view but its has some problem with small charts which has less content. We have one small chart and I thought to make it work nth-child selector but I don't know why it does not work. No am with something like this 
![amcharts-ui](https://user-images.githubusercontent.com/12906090/31837932-4a3eae18-b5f8-11e7-85f4-a757f7243674.jpg)

Let me know what you think about it

**Comment by realslimshanky** [comment]
@amitsin6h I suggest we make the image horizontally scrollable keeping the width of the div containing the image below screen size. This way we don't have to make a compromise with the image size and quality.

**Comment by amitsin6h** [comment]
#101 
@realslimshanky review it.

**Comment by realslimshanky** [comment]
Closing this issue since it has been fixed in #101
