### ISSUE TITLE
Links on navbar broken on blog

### ISSUE THREAD

**Issue by k4rtik** [pythonindia/inpycon-blog#8]
Most nav links on the top navbar at https://in.pycon.org/blog/2015/registrations-open.html are broken.

E.g. Clicking on Home or PyConIndia logo takes me to https://in.pycon.org/blog/2015/registrations-open.html#home

**Comment by kirang89** [comment]
This has been fixed.

**Comment by k4rtik** [comment]
The link to homepage is still wrong on the primary logo on the top left (unless it's not deployed yet).

Please feel free to close the issue, when you see fit. Thanks.

**Comment by kirang89** [comment]
Ah yes. I guess we can't close it yet.

**Comment by kracekumar** [comment]
It is fixed now. Thanks @k4rtik and @kirang89. Closing it now. Don't forget to force reload the page to check the changes.
