### ISSUE TITLE
A blog announcing Pipal Academy as the Associate Sponsor

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon-blog#90]
Use this write-up to create the blog.
```Pipal Academy is a collective of experienced technologists, who care deeply about the art of software development. They offer in-depth courses on niche technical topics. Pipal Academy regularly conducts public workshops in Bangalore and also offer on-site corporate training. Their courses are targeted at professional software developers and they make sure they are hands-on and interactive.```

**Comment by vipulgupta2048** [comment]
I would like to take this up.

**Comment by realslimshanky** [comment]
@vipulgupta2048 thank you, waiting for your PR.

**Comment by vipulgupta2048** [comment]
PR submitted  #91

**Comment by realslimshanky** [comment]
Closing the issue since the PR #91 has been merged which fixes it.
