### ISSUE TITLE
[UI] favicon is missing on PyCon Blog "https://in.pycon.org/blog/" 

### ISSUE THREAD

**Issue by omi10859** [pythonindia/inpycon-blog#93]

**Comment by realslimshanky** [comment]
@omi10859 would you like to work on this issue?

**Comment by omi10859** [comment]
yup!

**Comment by ankitrai96** [comment]
@realslimshanky I would like to work on this issue if no one has called dibs on it yet.

**Comment by realslimshanky** [comment]
@anktirai96 great. Let's check out your PR.
