### ISSUE TITLE
Blog about community spaces

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon-blog#95]
PyCon India recently announced about the community spaces and how one can apply for that. A blog is needed regarding the same. One has to use the same email [1] from the mailing list for the blog.
[1] https://mail.python.org/pipermail/inpycon/2017-October/011197.html

**Comment by Pradhvan** [comment]
I can help with this issue.

**Comment by realslimshanky** [comment]
@Pradhvan great. Will wait for your PR.

**Comment by kracekumar** [comment]
@Pradhvan Will you be able to get this done by today? This is a high priority we need to publicize and get response.

**Comment by Pradhvan** [comment]
Yes I will do a PR today. The blog is up for review in the volunteer channel.

**Comment by realslimshanky** [comment]
@Pradhvan please make the PR, we can review it there as well.

**Comment by Pradhvan** [comment]
Please review PR [#97](https://github.com/pythonindia/inpycon-blog/pull/97)

**Comment by realslimshanky** [comment]
@Pradhvan thank you for your contribution :pizza:
